version: "3.9"
services:

  db:
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: bot
      POSTGRES_PASSWORD: bot
      POSTGRES_DB: bot
    volumes:
      - "./pg-data:/var/lib/postgresql/data"
    # restart: always

  bot:
    build: .
    env_file:
      - .env
    command: python run.py
    # restart: always
