name: CI

on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  GH_IMAGE_ID: ghcr.io/${{ github.repository_owner }}/tg-likes-bot
  YA_IMAGE_ID: cr.yandex/${{ secrets.YA_CR_ID }}/tg-likes-bot

jobs:

  version:

    runs-on: ubuntu-latest

    permissions:
      contents: write
      issues: write
      pull-requests: write
  
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v3
        if: github.ref == 'refs/heads/master'
        id: semantic
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build:
    needs:
      - version

    runs-on: ubuntu-latest
    
    permissions:
      packages: write
      contents: read

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Build and push Docker image
        id: build
        run: |
          VERSION=$(git describe --tags --always | cut -c 2-)
          docker build . --file Dockerfile --tag $GH_IMAGE_ID:$VERSION --tag $GH_IMAGE_ID:latest
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          docker push $GH_IMAGE_ID:$VERSION
          echo "${{ secrets.YA_OAUTH }}" | docker login cr.yandex -u oauth --password-stdin
          docker tag $GH_IMAGE_ID:$VERSION $YA_IMAGE_ID:$VERSION
          docker push $YA_IMAGE_ID:$VERSION
          echo "gh_image=$GH_IMAGE_ID:$VERSION" >> $GITHUB_OUTPUT
          echo "ya_image=$YA_IMAGE_ID:$VERSION" >> $GITHUB_OUTPUT

    outputs:
      gh_image: ${{ steps.build.outputs.gh_image }}
      ya_image: ${{ steps.build.outputs.ya_image }}

  quality:
    needs:
      - build

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: bot
          POSTGRES_PASSWORD: bot
          POSTGRES_DB: bot
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    container:
      image: ${{ needs.build.outputs.gh_image }}
      env:
        APP_DB_HOST: postgres

    steps:
      - name: Run tests
        run: |
          cd /app
          scripts/lint.sh
          scripts/test.sh

  deploy:
    needs:
      - build
      - quality

    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Yandex SLS Containers
        run: |
          curl -sSL https://storage.yandexcloud.net/yandexcloud-yc/install.sh | bash
          exec bash
          yc --token ${{ secrets.YA_OAUTH }} --folder-id ${{ secrets.YA_FOLDER_ID }} serverless container revisions deploy \
            --container-name tg-likes-bot \
            --memory 1GB \
            --cores 1 \
            --core-fraction 20 \
            --execution-timeout 5s \
            --concurrency 10 \
            --service-account-id ${{ secrets.YA_SERVICE_ACCOUNT_ID }} \
            --image ${{ needs.build.outputs.ya_image }} \
            --command python \
            --args run.py \
            --zone-instances-limit 1 \
            --log-group-name tg-likes-bot
